### ISSUE TITLE
Installation error on Windows - unable to get local issuer certificate

### ISSUE THREAD

**Issue by nalla-vishalkumar** [hcl-dx/WebDevToolkitForDx#19]
Hi,

I am unable to install the tool kit on windows due to the following error:

Node version: v14.17.1
NPM version: 6.14.13

![image](https://user-images.githubusercontent.com/4252775/131119324-cdd6249f-ba1b-4550-a6ad-d87268f8deba.png)

I have also followed the proxy instructions under https://www.npmjs.com/package/nw. Since i am not using any proxy server it is not applicable for my case.

**Note: This is happening on HCL Laptops, not with personal laptops. We tried installing on personal latpop, it was installed successfully.** 

Thanks
Vishal

**Comment by codyburleson** [comment]
I have the same problem attempting to install on Windows:

```bash
C:\digexp-toolkit-2.0.0>npm install -g
npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
C:\Users\cxb6798\AppData\Roaming\npm\dxdashboard -> C:\Users\cxb6798\AppData\Roaming\npm\node_modules\digexp-toolkit\bin\dxdashboard
C:\Users\cxb6798\AppData\Roaming\npm\dxwcmdesigns -> C:\Users\cxb6798\AppData\Roaming\npm\node_modules\digexp-toolkit\bin\dxwcmdesigns
C:\Users\cxb6798\AppData\Roaming\npm\dxsync -> C:\Users\cxb6798\AppData\Roaming\npm\node_modules\digexp-toolkit\bin\dxsync
C:\Users\cxb6798\AppData\Roaming\npm\sp -> C:\Users\cxb6798\AppData\Roaming\npm\node_modules\digexp-toolkit\bin\sp

> pathwatcher@8.1.0 install C:\digexp-toolkit-2.0.0\node_modules\pathwatcher
> node load.js || node-gyp rebuild

Error: The module '\\?\C:\digexp-toolkit-2.0.0\node_modules\pathwatcher\build\Release\pathwatcher.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (C:\digexp-toolkit-2.0.0\node_modules\pathwatcher\lib\main.js:4:13)
    at Object.<anonymous> (C:\digexp-toolkit-2.0.0\node_modules\pathwatcher\lib\main.js:266:4)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'ERR_DLOPEN_FAILED'
}
Unable to watch files due to missing pathwatcher module. Install the module from source with the --from-source flag: npm install -g --from-source
Please provide feedback to the author of this module about the missing pre-compiled dependencies.
Your system information: win32 (Platform) / x64 (Architecture)


> nw@0.42.0 postinstall C:\digexp-toolkit-2.0.0\node_modules\nw
> node scripts/install.js

npm WARN notsup Unsupported engine for dxsync@1.0.3: wanted: {"node":"^12","npm":"^6"} (current: {"node":"14.18.1","npm":"6.14.15"})
npm WARN notsup Not compatible with your version of node/npm: dxsync@1.0.3
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (..\..\..\..\..\digexp-toolkit-2.0.0\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ digexp-toolkit@2.0.0
added 651 packages from 439 contributors in 96.737s

C:\digexp-toolkit-2.0.0>
```

**Comment by ThomasHurek** [comment]
@nalla-vishalkumar The module is not signed so you need to request according admin permissions on the laptop.

**Comment by ThomasHurek** [comment]
@codyburleson The issue you reported is actually different from @nalla-vishalkumar - in your case the issue seems to be the node version:
Unsupported engine for dxsync@1.0.3: wanted: {"node":"^12","npm":"^6"} (current: {"node":"14.18.1","npm":"6.14.15"})

You seem to have 14.8.1 but we specified 12.6 for a submodule. Would suggest to use nvm and switch to node 12.x.

**Comment by codyburleson** [comment]
Actually, I'm not sure what changed, but the last time I tried this on the same machine, it worked for me. So, I guess I'm good for now! Thanks for your feedback though.

**Comment by codyburleson** [comment]
> You seem to have 14.8.1 but we specified 12.6 for a submodule. Would suggest to use nvm and switch to node 12.x.

Actually, I'm not sure what changed, but the last time I tried this on the same machine, it worked for me. So, I guess I'm good for now! Thanks for your feedback.
